
- hosts: localhost
  tasks:
    - include_vars: "{{ playbook_dir }}/vars.yml"
    - name: Wait for connection
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 300
      loop:
        "{{ nodes }}"

- hosts: REGISTRY
  user: ubuntu
  become: yes
  tasks:
    - name: Get helm
      get_url:
          url: https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          dest: /tmp/helm.tar.gz
      
    - name: Extract helm
      unarchive:
          src: /tmp/helm.tar.gz
          dest: /usr/local/bin/
          remote_src: yes
          owner: root
          group: root
          mode: "0755"
          extra_opts: 
            - --strip-components=1
            - --wildcards
            - '*/helm'

- hosts: REGISTRY
  user: ubuntu  
  tasks:
    - name: Clear directory
      file:
        path: /home/ubuntu/istio
        state: absent
 
    - name: Create directory
      file:
        path: /home/ubuntu/istio
        state: directory
 
    - name: Download istio
      get_url:
        url: https://istio.io/downloadIstio
        dest: /home/ubuntu/istio
      register: apt_res
      retries: 300
      delay: 10
      until: apt_res is success          
    
    - name: Run istio script
      shell: |
        cd /home/ubuntu/istio 
        bash downloadIstioCandidate.sh
      register: apt_res
      retries: 300
      delay: 10
      until: apt_res is success          
        

    - name: Install istio
      shell: |
        cd /home/ubuntu/istio        
        cd `ls | grep istio`
        bin/istioctl install --set profile=demo -y
      register: apt_res
      retries: 300
      delay: 10
      until: apt_res is success  

      args:
        executable: /bin/bash

    - name: Kiali, prometheus, grafana, jeagger
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/kiali.yaml
        kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/prometheus.yaml
        kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/grafana.yaml
        kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/jaeger.yaml
        for p in kiali prometheus grafana; do
          kubectl -n istio-system expose service ${p} --name ${p}-external --type LoadBalancer
        done
        
      register: apt_res
      retries: 300
      delay: 10
      until: apt_res is success  
      args:
        executable: /bin/bash        
      

