kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-my-release-mysql-0 
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

