---

  - include_vars: "{{ playbook_dir }}/config.yml"
  - include_vars: "{{ playbook_dir }}/vars.yml"  
  
# tasks file for amf
  - name: Update
    apt:
      name: '*'
      state: 'latest'
      update_cache: yes
    retries: 300
    delay: 10

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file    

  - name: Reboot
    reboot:
      msg: Reboot triggered
      reboot_timeout: 360
    when: reboot_required_file.stat.exists == true


  - name: etc_hosts
    template:
      src: hosts.j2
      dest: /etc/hosts

